distributable:
  url: https://github.com/promptexecution/rust-cargo-docs-rag-mcp/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

versions:
  github: promptexecution/rust-cargo-docs-rag-mcp

dependencies:
  openssl.org: '>=1.1'

build:
  dependencies:
    rust-lang.org: '>=1.91'
    rust-lang.org/cargo: '*'
  script:
    - cargo install --locked \
        --root={{ prefix }} \
        --path=. \
        --bin cratedocs

provides:
  - bin/cratedocs

test:
  - cratedocs version | grep {{version}}
